"use client";

import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useState } from "react";

type Summary={operational_services:number;impaired_services:number;active_deployments:number;open_incidents:number;upcoming_maintenance:number};
type Service={platform_service_id:string;service_code:string;service_name:string;service_type:string;environment:string;status:string;owner_team:string|null;health_endpoint:string|null};
type Deployment={platform_deployment_id:string;service_name:string;version:string;commit_sha:string|null;environment:string;status:string;created_at:string};
type Incident={platform_incident_id:string;incident_code:string;title:string;severity:string;status:string;service_name:string|null;detected_at:string};
type Maintenance={platform_maintenance_window_id:string;maintenance_name:string;service_name:string|null;starts_at:string;ends_at:string;impact_level:string;status:string};
type Workspace={services:Service[];deployments:Deployment[];incidents:Incident[];maintenance:Maintenance[];summary:Summary};
const empty:Workspace={services:[],deployments:[],incidents:[],maintenance:[],summary:{operational_services:0,impaired_services:0,active_deployments:0,open_incidents:0,upcoming_maintenance:0}};

export default function PlatformOperationsPage(){
 const [workspace,setWorkspace]=useState<Workspace>(empty); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const [serviceForm,setServiceForm]=useState({serviceCode:"",serviceName:"",serviceType:"APPLICATION",environment:"PRODUCTION",ownerTeam:"",healthEndpoint:"",description:""});
 const [deploymentForm,setDeploymentForm]=useState({platformServiceId:"",version:"",commitSha:"",environment:"PRODUCTION"});
 const [incidentForm,setIncidentForm]=useState({platformServiceId:"",incidentCode:"",title:"",severity:"SEV3",summary:"",commanderUserId:""});
 const [maintenanceForm,setMaintenanceForm]=useState({platformServiceId:"",maintenanceName:"",startsAt:"",endsAt:"",impactLevel:"LOW",notes:""});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/operator/platform-operations?q=${encodeURIComponent(query)}`,{cache:"no-store"});const d=await r.json() as Workspace&{error?:string};if(!r.ok)throw new Error(d.error||"PLATFORM_OPERATIONS_UNAVAILABLE");setWorkspace(d);}catch(e){setError(e instanceof Error?e.message:"PLATFORM_OPERATIONS_UNAVAILABLE");}finally{setLoading(false);}},[query]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{const first=workspace.services[0];if(first){if(!deploymentForm.platformServiceId)setDeploymentForm(v=>({...v,platformServiceId:first.platform_service_id}));if(!incidentForm.platformServiceId)setIncidentForm(v=>({...v,platformServiceId:first.platform_service_id}));if(!maintenanceForm.platformServiceId)setMaintenanceForm(v=>({...v,platformServiceId:first.platform_service_id}));}},[workspace.services,deploymentForm.platformServiceId,incidentForm.platformServiceId,maintenanceForm.platformServiceId]);
 const metrics=useMemo<Array<[string,number]>>(()=>[["Operational services",Number(workspace.summary.operational_services||0)],["Impaired services",Number(workspace.summary.impaired_services||0)],["Active deployments",Number(workspace.summary.active_deployments||0)],["Open incidents",Number(workspace.summary.open_incidents||0)],["Upcoming maintenance",Number(workspace.summary.upcoming_maintenance||0)]],[workspace.summary]);
 async function post(body:Record<string,unknown>){setError("");const r=await fetch("/api/operator/platform-operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok){setError(d.error||"PLATFORM_OPERATIONS_UNAVAILABLE");return false;}await load();return true;}
 async function act(itemType:string,itemId:string,action:string){setError("");const r=await fetch("/api/operator/platform-operations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemType,itemId,action})});const d=await r.json() as {error?:string};if(!r.ok){setError(d.error||"PLATFORM_OPERATIONS_UNAVAILABLE");return;}await load();}
 async function createService(e:FormEvent<HTMLFormElement>){e.preventDefault();if(await post({entityType:"SERVICE",...serviceForm}))setServiceForm({serviceCode:"",serviceName:"",serviceType:"APPLICATION",environment:"PRODUCTION",ownerTeam:"",healthEndpoint:"",description:""});}
 async function createDeployment(e:FormEvent<HTMLFormElement>){e.preventDefault();if(await post({entityType:"DEPLOYMENT",...deploymentForm}))setDeploymentForm(v=>({...v,version:"",commitSha:""}));}
 async function createIncident(e:FormEvent<HTMLFormElement>){e.preventDefault();if(await post({entityType:"INCIDENT",...incidentForm}))setIncidentForm(v=>({...v,incidentCode:"",title:"",summary:"",commanderUserId:""}));}
 async function createMaintenance(e:FormEvent<HTMLFormElement>){e.preventDefault();if(await post({entityType:"MAINTENANCE",...maintenanceForm}))setMaintenanceForm(v=>({...v,maintenanceName:"",startsAt:"",endsAt:"",notes:""}));}
 return <main style={{padding:24,display:"grid",gap:24}}><header><p style={{margin:0,opacity:.7}}>Phase 20</p><h1 style={{marginBottom:8}}>Platform Operations</h1><p style={{margin:0,opacity:.75}}>Service health, deployments, incidents, maintenance windows, and operational control.</p></header>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:12}}>{metrics.map(([l,v])=><Metric key={l} label={l} value={v}/>)}</section>
 <section style={{display:"flex",gap:8,flexWrap:"wrap"}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search services" style={{minWidth:260,padding:10}}/><button onClick={()=>void load()} disabled={loading}>Refresh</button></section>
 {error?<p role="alert" style={{padding:12,border:"1px solid currentColor",borderRadius:8}}>{error}</p>:null}
 <Panel title="Register service"><form onSubmit={createService} style={formStyle}><input required value={serviceForm.serviceCode} onChange={e=>setServiceForm({...serviceForm,serviceCode:e.target.value})} placeholder="Service code"/><input required value={serviceForm.serviceName} onChange={e=>setServiceForm({...serviceForm,serviceName:e.target.value})} placeholder="Service name"/><select value={serviceForm.serviceType} onChange={e=>setServiceForm({...serviceForm,serviceType:e.target.value})}>{["APPLICATION","DATABASE","QUEUE","WORKER","EXTERNAL_DEPENDENCY"].map(v=><option key={v}>{v}</option>)}</select><select value={serviceForm.environment} onChange={e=>setServiceForm({...serviceForm,environment:e.target.value})}>{["PRODUCTION","STAGING","DEVELOPMENT"].map(v=><option key={v}>{v}</option>)}</select><input value={serviceForm.ownerTeam} onChange={e=>setServiceForm({...serviceForm,ownerTeam:e.target.value})} placeholder="Owner team"/><input value={serviceForm.healthEndpoint} onChange={e=>setServiceForm({...serviceForm,healthEndpoint:e.target.value})} placeholder="Health endpoint"/><button type="submit">Register service</button></form></Panel>
 <Panel title="Create deployment"><form onSubmit={createDeployment} style={formStyle}><ServiceSelect services={workspace.services} value={deploymentForm.platformServiceId} onChange={v=>setDeploymentForm({...deploymentForm,platformServiceId:v})}/><input required value={deploymentForm.version} onChange={e=>setDeploymentForm({...deploymentForm,version:e.target.value})} placeholder="Version"/><input value={deploymentForm.commitSha} onChange={e=>setDeploymentForm({...deploymentForm,commitSha:e.target.value})} placeholder="Commit SHA"/><select value={deploymentForm.environment} onChange={e=>setDeploymentForm({...deploymentForm,environment:e.target.value})}>{["PRODUCTION","STAGING","DEVELOPMENT"].map(v=><option key={v}>{v}</option>)}</select><button type="submit">Queue deployment</button></form></Panel>
 <Panel title="Open incident"><form onSubmit={createIncident} style={formStyle}><ServiceSelect services={workspace.services} value={incidentForm.platformServiceId} onChange={v=>setIncidentForm({...incidentForm,platformServiceId:v})}/><input required value={incidentForm.incidentCode} onChange={e=>setIncidentForm({...incidentForm,incidentCode:e.target.value})} placeholder="Incident code"/><input required value={incidentForm.title} onChange={e=>setIncidentForm({...incidentForm,title:e.target.value})} placeholder="Title"/><select value={incidentForm.severity} onChange={e=>setIncidentForm({...incidentForm,severity:e.target.value})}>{["SEV1","SEV2","SEV3","SEV4"].map(v=><option key={v}>{v}</option>)}</select><input value={incidentForm.summary} onChange={e=>setIncidentForm({...incidentForm,summary:e.target.value})} placeholder="Summary"/><button type="submit">Open incident</button></form></Panel>
 <Panel title="Schedule maintenance"><form onSubmit={createMaintenance} style={formStyle}><ServiceSelect services={workspace.services} value={maintenanceForm.platformServiceId} onChange={v=>setMaintenanceForm({...maintenanceForm,platformServiceId:v})}/><input required value={maintenanceForm.maintenanceName} onChange={e=>setMaintenanceForm({...maintenanceForm,maintenanceName:e.target.value})} placeholder="Maintenance name"/><input required type="datetime-local" value={maintenanceForm.startsAt} onChange={e=>setMaintenanceForm({...maintenanceForm,startsAt:e.target.value})}/><input required type="datetime-local" value={maintenanceForm.endsAt} onChange={e=>setMaintenanceForm({...maintenanceForm,endsAt:e.target.value})}/><select value={maintenanceForm.impactLevel} onChange={e=>setMaintenanceForm({...maintenanceForm,impactLevel:e.target.value})}>{["LOW","MEDIUM","HIGH","FULL_OUTAGE"].map(v=><option key={v}>{v}</option>)}</select><button type="submit">Schedule maintenance</button></form></Panel>
 <Panel title="Services"><Table columns={["Code","Service","Type","Environment","Status","Actions"]} rows={workspace.services.map(x=>[x.service_code,x.service_name,x.service_type,x.environment,x.status,<Actions key={x.platform_service_id} items={[["Restore","RESTORE"],["Degrade","DEGRADE"],["Outage","OUTAGE"]]} run={a=>void act("SERVICE",x.platform_service_id,a)}/>])}/></Panel>
 <Panel title="Deployments"><Table columns={["Service","Version","Commit","Environment","Status","Actions"]} rows={workspace.deployments.map(x=>[x.service_name,x.version,x.commit_sha||"—",x.environment,x.status,<Actions key={x.platform_deployment_id} items={[["Start","START"],["Succeed","SUCCEED"],["Fail","FAIL"],["Rollback","ROLLBACK"]]} run={a=>void act("DEPLOYMENT",x.platform_deployment_id,a)}/>])}/></Panel>
 <Panel title="Incidents"><Table columns={["Code","Title","Service","Severity","Status","Actions"]} rows={workspace.incidents.map(x=>[x.incident_code,x.title,x.service_name||"—",x.severity,x.status,<Actions key={x.platform_incident_id} items={[["Acknowledge","ACKNOWLEDGE"],["Resolve","RESOLVE"],["Close","CLOSE"]]} run={a=>void act("INCIDENT",x.platform_incident_id,a)}/>])}/></Panel>
 <Panel title="Maintenance windows"><Table columns={["Name","Service","Start","End","Impact","Status","Actions"]} rows={workspace.maintenance.map(x=>[x.maintenance_name,x.service_name||"—",new Date(x.starts_at).toLocaleString(),new Date(x.ends_at).toLocaleString(),x.impact_level,x.status,<Actions key={x.platform_maintenance_window_id} items={[["Start","START"],["Complete","COMPLETE"],["Cancel","CANCEL"]]} run={a=>void act("MAINTENANCE",x.platform_maintenance_window_id,a)}/>])}/></Panel>{loading?<p>Loading platform operations…</p>:null}</main>;
}
function Metric({label,value}:{label:string;value:number}){return <article style={panelStyle}><small>{label}</small><div style={{fontSize:28,fontWeight:700}}>{value}</div></article>}
function Panel({title,children}:{title:string;children:ReactNode}){return <section style={panelStyle}><h2>{title}</h2>{children}</section>}
function ServiceSelect({services,value,onChange}:{services:Service[];value:string;onChange:(v:string)=>void}){return <select required value={value} onChange={e=>onChange(e.target.value)}><option value="">Select service</option>{services.map(x=><option key={x.platform_service_id} value={x.platform_service_id}>{x.service_name}</option>)}</select>}
function Actions({items,run}:{items:Array<[string,string]>;run:(a:string)=>void}){return <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{items.map(([l,a])=><button key={a} onClick={()=>run(a)}>{l}</button>)}</div>}
function Table({columns,rows}:{columns:string[];rows:ReactNode[][]}){return <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{columns.map(c=><th key={c} style={cellStyle}>{c}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} style={cellStyle}>{c}</td>)}</tr>):<tr><td colSpan={columns.length} style={cellStyle}>No records</td></tr>}</tbody></table></div>}
const panelStyle={border:"1px solid rgba(127,127,127,.35)",borderRadius:12,padding:16} as const;
const formStyle={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10} as const;
const cellStyle={textAlign:"left",padding:10,borderBottom:"1px solid rgba(127,127,127,.25)",verticalAlign:"top"} as const;
